#!/usr/bin/env bash
echo "checkin for updates......"
sleep 2
sudo apt-get update && sudo apt-get upgrade -y
echo "Installing ..."
sleep 2
cd ~/Documents/tunnel/algo-master
sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip python-setuptools python-virtualenv -y
echo ""
sleep 2
echo "OK - let's doooz it ......"
sudo python -m virtualenv env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
echo "installing"
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-add-repository ppa:ansible/ansible
sudo apt-get install ansible -y
sudo chmod +x ./algo
ssh-keygen
cat ~/.ssh/id_rsa.pub
sleep 1
./algo

